// Runtime configuration bootstrap for Codex Vitae.
//
// HOW TO CONFIGURE LOCALLY
// -------------------------
// 1. The checked-in INLINE_RUNTIME_CONFIG below contains this app's public
//    Firebase web configuration so the GitHub Pages build can boot. Firebase
//    web API keys identify a project; they are not admin secrets. Protect
//    project data with Firebase Auth, Firestore, and Storage security rules.
// 2. To override those defaults, create a `config.runtime.json` next to this
//    file during deployment that contains the same shape as
//    INLINE_RUNTIME_CONFIG. The loader will fetch it at runtime.
// 3. When hosting on Firebase Hosting, you may rely on its automatic
//    discovery endpoint at `/__/firebase/init.json`.
//
// This loader allows deploy-specific configuration without blocking the
// public GitHub Pages app from booting. It hydrates `window.__CODEX_CONFIG__`
// from a few potential sources:
//   1. Inline values defined in INLINE_RUNTIME_CONFIG (this file).
//   2. Any configuration assigned to `window.__CODEX_CONFIG__` before this
//      script executes (for example, an inline script generated by the hosting
//      platform).
//   3. A static JSON file (`config.runtime.json`) that can be generated during
//      deployment with the correct credentials.
//   4. Firebase Hosting's discovery endpoint (`/__/firebase/init.json`), which
//      exposes the app's Firebase configuration at runtime without embedding it
//      in the repository.
//
// When a valid configuration is discovered, the loader resolves the
// `window.__CODEX_CONFIG_READY__` promise so the rest of the app can start
// safely.

(function bootstrapCodexRuntimeConfig(global) {
  const REQUIRED_FIREBASE_KEYS = Object.freeze([
    'apiKey',
    'authDomain',
    'projectId',
    'appId'
  ]);

  const DEFAULT_CONFIG = Object.freeze({
    firebaseConfig: {
      apiKey: 'AIzaSyC11QPS3V1qZNGIQdEYp_Odsy5UoGl-fTo',
      authDomain: 'codex-vitae-7b7c8.firebaseapp.com',
      projectId: 'codex-vitae-7b7c8',
      storageBucket: 'codex-vitae-7b7c8.appspot.com',
      messagingSenderId: '1078938226885',
      appId: '1:1078938226885:web:918e532b901f2390173f27',
      measurementId: 'G-0E0Z4R2T73'
    },
    backendUrl: '',
    firebaseHostingOrigin: 'https://codex-vitae-470801.web.app'
  });

  // Public Firebase web configuration for the hosted Codex Vitae app. These
  // values are required for the login screen to initialize on GitHub Pages;
  // authorization remains controlled by Firebase security rules. Override them
  // with `window.__CODEX_CONFIG__` or `config.runtime.json` for another project.
  const INLINE_RUNTIME_CONFIG = {
    firebaseConfig: {
codex/review-codex-vitae-project-objectives-b4xhg4
      apiKey: 'AIzaSyC11QPS3V1qZNGIQdEYp_Odsy5UoGl-fTo',
      authDomain: 'codex-vitae-7b7c8.firebaseapp.com',
      projectId: 'codex-vitae-7b7c8',
      storageBucket: 'codex-vitae-7b7c8.appspot.com',
      messagingSenderId: '1078938226885',
      appId: '1:1078938226885:web:918e532b901f2390173f27',
      measurementId: 'G-0E0Z4R2T73'
 codex/review-codex-vitae-project-objectives-38mi3z

 codex/review-codex-vitae-project-objectives-pb5syj

 codex/review-codex-vitae-project-objectives-0858z4

      apiKey: '',
      authDomain: '',
      projectId: '',
      storageBucket: '',
      messagingSenderId: '',
      appId: '',
      measurementId: ''
main
 main
 main
 main
    },
    backendUrl: '',
    firebaseHostingOrigin: ''
  };

  function cloneDefaultConfig() {
    return {
      firebaseConfig: { ...DEFAULT_CONFIG.firebaseConfig },
      backendUrl: DEFAULT_CONFIG.backendUrl,
      firebaseHostingOrigin: DEFAULT_CONFIG.firebaseHostingOrigin
    };
  }

  function mergeConfig(target, source) {
    if (!source || typeof source !== 'object') {
      return target;
    }

    if (source.firebaseConfig && typeof source.firebaseConfig === 'object') {
      target.firebaseConfig = target.firebaseConfig || {};
      for (const key of Object.keys(source.firebaseConfig)) {
        const value = source.firebaseConfig[key];
        if (typeof value === 'string') {
          target.firebaseConfig[key] = value;
        }
      }
    }

    if (typeof source.backendUrl === 'string') {
      target.backendUrl = source.backendUrl;
    }

    if (typeof source.firebaseHostingOrigin === 'string') {
      target.firebaseHostingOrigin = source.firebaseHostingOrigin.trim();
    }

    return target;
  }

  function hasRequiredFirebaseConfig(config) {
    if (!config || typeof config !== 'object') {
      return false;
    }
    return REQUIRED_FIREBASE_KEYS.every(key => {
      const value = config[key];
      return typeof value === 'string' && value.trim().length > 0;
    });
  }

  function finalizeConfig(resolve, baseConfig) {
    const resolvedConfig = baseConfig || cloneDefaultConfig();
    global.__CODEX_CONFIG__ = resolvedConfig;
    resolve(resolvedConfig);
  }

  const initialConfig = cloneDefaultConfig();
  mergeConfig(initialConfig, INLINE_RUNTIME_CONFIG);
  mergeConfig(initialConfig, global.__CODEX_CONFIG__);

  let resolveReady;
  const readyPromise = new Promise(resolve => {
    resolveReady = resolve;
  });

  // Expose the promise immediately so dependent scripts can await it.
  global.__CODEX_CONFIG_READY__ = readyPromise;

  if (hasRequiredFirebaseConfig(initialConfig.firebaseConfig)) {
    finalizeConfig(resolveReady, initialConfig);
    return;
  }

  const runtimeLoaders = [
    async function loadFromRuntimeJson() {
      const response = await fetch('config.runtime.json', { cache: 'no-store' });
      if (!response.ok) {
        throw new Error(`config.runtime.json request failed with status ${response.status}`);
      }
      const data = await response.json();
      const normalized = {};
      if (data && typeof data === 'object') {
        if (data.firebaseConfig && typeof data.firebaseConfig === 'object') {
          normalized.firebaseConfig = data.firebaseConfig;
        } else {
          normalized.firebaseConfig = data;
        }
        if (typeof data.backendUrl === 'string') {
          normalized.backendUrl = data.backendUrl;
        }
        if (typeof data.firebaseHostingOrigin === 'string') {
          normalized.firebaseHostingOrigin = data.firebaseHostingOrigin;
        }
      }
      return normalized;
    }
  ];

  if (typeof initialConfig.firebaseHostingOrigin === 'string' && initialConfig.firebaseHostingOrigin.trim()) {
    runtimeLoaders.push(async function loadFromConfiguredFirebaseHosting() {
      const origin = initialConfig.firebaseHostingOrigin.trim();
      const sanitizedOrigin = origin.replace(/\/+$/, '');
      const requestUrl = `${sanitizedOrigin}/__/firebase/init.json`;
      const response = await fetch(requestUrl, { cache: 'no-store' });
      if (!response.ok) {
        throw new Error(`Firebase init.json request to ${requestUrl} failed with status ${response.status}`);
      }

      const data = await response.json();
      if (!data || typeof data !== 'object') {
        throw new Error('Firebase init.json response from configured hosting did not contain an object.');
      }

      return { firebaseConfig: data };
    });
  }

  runtimeLoaders.push(async function loadFromFirebaseHosting() {
    const response = await fetch('/__/firebase/init.json', { cache: 'no-store' });
    if (!response.ok) {
      throw new Error(`Firebase init.json request failed with status ${response.status}`);
    }
    const data = await response.json();
    if (!data || typeof data !== 'object') {
      throw new Error('Firebase init.json response did not contain an object.');
    }

    // Firebase returns the config at the top level. Preserve any existing backendUrl.
    return { firebaseConfig: data };
  });

  (async () => {
    const merged = cloneDefaultConfig();
    mergeConfig(merged, initialConfig);

    for (const loader of runtimeLoaders) {
      try {
        const loadedConfig = await loader();
        mergeConfig(merged, loadedConfig);
        if (hasRequiredFirebaseConfig(merged.firebaseConfig)) {
          finalizeConfig(resolveReady, merged);
          return;
        }
      } catch (error) {
        console.warn('Codex Vitae runtime config loader failed.', error);
      }
    }

    finalizeConfig(resolveReady, merged);
  })();
})(window);
